controller/contribution/contribution.php

[ticket/653] Use attachment id in version check download links

---

styles/prosilver/template/common/contribution_details.html

https://tracker.phpbb.com/browse/CUSTDB-648

Remove phpBB version section from contribution details page

---

language/en/types/extension.php

Add in link information for extension denial

---

includes/types/extension.php

Note every extension added to Titania since around Feb 6th will need to be resubmitted by the authors, or repacked to fix the problems caused here.

[ticket/659] Fix version check changes to composer.json

---

composer.json

https://tracker.phpbb.com/browse/CUSTDB-694
CUSTDB-694

Explicitly state that phpbb/epv is in dev stability

---

files/colorizeit/index.htm
files/faq/index.htm
files/queue/index.htm
files/queue_discussion/index.htm
files/revisions/index.htm
files/screenshots/index.htm
files/support/index.htm
files/translations/index.htm

We need to do it because plupload tries to create a subdirectory and
copy inside the index.htm file.
[CUSTDB-688](https://tracker.phpbb.com/browse/CUSTDB-688)

[ticket/688] Create uploads directories

---

config/config.php
config/controllers.yml
config/routes/general.yml
controller/composer.php
controller/helper.php
includes/manage_tools/rebuild_packages_list.php
includes/objects/contribution.php
includes/objects/revision.php
includes/tools/composer_package_manager.php
includes/types/extension.php
migrations/composer_integration.php

New composer repository PR
customisation-db#149

Composer repository

---

.htaccess
assets/.htaccess
files/.htaccess
includes/.htaccess
language/.htaccess
store/.htaccess
styles/.htaccess
styles/prosilver/template/.htaccess

Prevent all access except to js|css|png|gif|jpg files in the assets and styles directories.
@Noxwizard

Harden access control.

---

composer.lock

@DavidIQ Please merge (And after that make it so we can see it on .com, as I have no clue how)

Update EPV to 0.0.7

---

styles/all/template/event/navbar_header_profile_list_after.html

As per [CUSTDB-669](https://tracker.phpbb.com/browse/CUSTDB-669).

Add Contributions link everywhere

---

config/services.yml
controller/helper.php
controller/ucp/subscriptions.php
display.php
event/main_listener.php

This extends the previous PR #181 to actually make it work.

Really show My contributions-link

---

includes/overlords/contribs.php
includes/overlords/posts.php
includes/overlords/topics.php
language/en/common.php
sort.php

Change lang keys to avoid error in UCP

---

styles/prosilver/template/contributions/contribution_revision.html

EPV output is unformatted and kind of a mess:
This PR tries to correct it:

Format & fix EPV output

---

assets/javascript/ajax.js
styles/prosilver/template/common/post_list.html
styles/prosilver/template/faq_body.html
styles/prosilver/template/posting/posting_preview.html
styles/prosilver/theme/common.css

New BBCode system change's line breaks around lists. We now rely on CSS to add margin to bottom of lists.

Fix styling issues

---

language/en/types/translation.php

Please check the new wording, thank you! @phpbb/native 
@phpbb/extensions-team Feel free to review it.

Updates links to policies, adds a new point to test the language pack

---

SETUP.md
attachment/plupload.php
attachment/uploader.php
controller/index.php
includes/objects/revision.php
message/message.php

Fixes https://tracker.phpbb.com/browse/CUSTDB-756
Also addresses debug notices caused by https://github.com/phpbb/customisation-db/pull/212

Titania Minor FIxes

---

contribution/extension/type.php
language/en/types/extension.php

https://tracker.phpbb.com/projects/CUSTDB/issues/CUSTDB-713

More specific composer.json error messages

---

config/config.php

https://github.com/phpbb/website/pull/170

Update for 3.2.3 release

---

config/config.php
controller/author.php
controller/contribution/contribution.php
includes/objects/author.php
language/en/manage_tools.php
styles/prosilver/template/authors/author_details.html
styles/prosilver/template/authors/author_manage.html
styles/prosilver/template/contributions/demo.html

1. We don't use the contrib author real name field, so lets just remove it.
2. Some updates to the styles demo page (untested but these should fix the home links to phpbb.com).
3. A few fixes.

Updates to reduce phpbb.com specific hacks

---

styles/prosilver/theme/common.css

CSS styling fix:
https://tracker.phpbb.com/projects/CUSTDB/issues/CUSTDB-775

Fix styling bug with BBCode in revisions

---

styles/prosilver/template/index_body.html

This is meant to be merged after 
https://github.com/phpbb/customisation-db/pull/252

Restore the Customisation Database page title

---

event/main_listener.php
styles/prosilver/theme/common.css

This class is used by phpBB.com to add the banner/header artwork.

Permanently add a class to the body class for CSS/scripting options

---

styles/prosilver/template/common/revision_list.html
styles/prosilver/theme/common.css

https://tracker.phpbb.com/projects/CUSTDB/issues/CUSTDB-771
I couldn't see any functional reason to have the dropdown and it's just a simple HTML/CSS change to have the list comma separated instead.

CUSTDB-771 - Remove select box for version list

---

config.php

Add validation queue forums to dot-com config settings

---

assets/javascript/ajax.js
controller/author.php
controller/index.php
includes/objects/post.php
includes/overlords/contribs.php
language/en/common.php
styles/prosilver/template/index_body.html

New functionality which allows the user to filter by contribution status (all, approved, unapproved).
https://tracker.phpbb.com/projects/CUSTDB/issues/CUSTDB-680

CUSTDB-680 - Filter contributions by status

---

styles/prosilver/theme/custom.css

apple responsive rank img

---

assets/javascript/ajax.js
contribution/type/base.php
contribution/type/type_interface.php
controller/index.php
sort.php
styles/prosilver/template/index_body.html

Bugfixes for https://github.com/phpbb/customisation-db/pull/268
* Don't show the dropdown for types that the user doesn't have validate permissions for
* Add status to the pagination links

Bugfixes for approved status filter

---

styles/prosilver/theme/custom.css

Reverts phpbb/customisation-db#267

Revert "apple responsive rank img"

---

language/en/types/translation.php

for https://tracker.phpbb.com/browse/CUSTDB-787

Translation CDB links are updated for 3.2.x and new documatation

---

language/en/types/extension.php

https://tracker.phpbb.com/projects/CUSTDB/issues/CUSTDB-788

[CUSTDB-788] Change IRC link to the Discord/IRC page on phpbb.com

---

composer.json
composer.lock
contribution/translation/prevalidator.php

Symfony v2.8 compatibility

---

includes/objects/post.php
message/message.php

This change fixes a bug with Titania quick reply, whereby if a topic was locked then replying with quick reply would unlock it.

[CUSTDB-789] Fix quick reply unlocking bug

---

config/config.php

Support yml in main branch too

---

contribution/style/demo/demo.php
controller/contribution/base.php

Disable 3.1 styles demo

---

contribution/translation/prevalidator.php

This should fix the issue @Crizz0 mentioned of it always picking the 3.3.0 version (because it was the most recent), even if someone selected the 3.2 branch.
I did a test of this and I got different validation results based on the version I selected, so it appears to be performing as expected. eg:
_Fatal: 69, Error: 7, Warning: 39, Notice: 53_ for 3.3
_Fatal: 19, Error: 7, Warning: 35, Notice: 53_ for 3.2

Get latest lang pack of the selected branch

---

controller/helper.php

https://tracker.phpbb.com/browse/CUSTDB-801

[CUSTDB-801] Fix URL generated when script path is outside the the board root

---

contribution/style/demo/demo.php

This will preserver compatibility with MySQL when only_full_group_by is enabled

Add nonaggregated columns to group by clause

---

controller/manage/config_settings.php

The admin config settings form only shows fields for existing config data. That means when new phpbb_version branches are added (which is done by editing `config.php`) there's no way to save new configs that are branch specific for the new phpBB branch.
This PR should fix that. It will add fields for phpBB branches on settings that are branch specific, even if that setting does not have a saved value yet.
In this pic, the DB only has style path demo data stored for phpBB 3.0, 3.1 and 3.2. But you can see a field is added for 3.3 so it's now possible to add that setting too. 
If later a new 4.0 branch is added to phpbb_versions, then a 4.0 field will be available in the form above to save (or ignore) a new value for that branch too.

Shows and save data related to new phpbb branches

---

includes/overlords/contribs.php

https://tracker.phpbb.com/browse/CUSTDB-816
Caused by and related to https://github.com/phpbb/customisation-db/pull/296

[CUSTDB-816] username clean issue.

---

migrations/base.php

Fix issues related to PR #330

---

styles/prosilver/theme/demo.css

Fix broken style select display

---

config/services.yml

Cache service was changed to require event dispatcher.

Adjust cache service for 3.3.8-RC1 changes

---

controller/support.php
includes/overlords/topics.php

Following [this PR](https://github.com/phpbb/customisation-db/pull/342), this introduced an issue on support topic lists

Fix support topic lists
