- includes/types/mod.php
This should make it so people can no longer submit new MODs (the Modification option will no longer be visible to them when creating a new contribution, but they can still submit new revisions to validated MODs). @prototech
> Do not allow submission of new MODs

- includes/manage_tools/fix_left_right_ids.php
- includes/manage_tools/resync_contrib_count.php
- includes/manage_tools/resync_dotted_topics.php
- includes/manage_tools/update_release_topics.php
Since that all messages in the administration of Titania are simple message without back link, trigger_error can be used.
> Replace calls to undefined function trigger_back by triger_error

- styles/prosilver/template/contributions/contribution_faq.html
The FAQ's are scrunched down to 76% to make room for profiles, but there are no profiles to display. So this is just a remnant of relying on prosilver styling/classes. There's no reason the FAQs can't span the whole width of the post content area, so this little fix allows for that.
> Allow FAQ postbody to span 100%

- language/en/contributions.php
- styles/prosilver/template/common/contribution_details.html
This adds to the download button info box that appears a little text:
Validated for:
phpBB 3.1.X
There are always people who think the version we display in the download button means that the contribution is ONLY for that version of phpBB. I am hoping this little addition of info makes it clearer that the version of phpBB displayed is not a rule, it's just our way of showing what version of phpBB we used when validating the contrib.
> Add "Validated for: version #" to download button info

- contribution/extension/type.php
Some extensions are using `>=3.1.x` and not only `>=3.1.*`
> Improves the regex to fix common error in composer.json

- display.php
Children categories are not hidden when their parent is hidden.
> Fix hidden sub categories

- controller/search.php
This should resolve "Catchable fatal error: Argument 2 passed to phpbb\titania\controller\helper::route() must be of the type array, boolean given, called in /var/www/www.phpbb.com/website-current/old/community/ext/phpbb/titania/controller/search.php on line 546 and defined in /var/www/www.phpbb.com/website-current/old/community/ext/phpbb/titania/controller/helper.php on line 39"
> Prevent $params variable from being anything other than an array

- includes/constants.php
This is unnecessary and because this file is autoloaded, it means this file will kill anything (like phpunit) that doesn't have this constant defined.
> Remove IN_PHPBB check

- styles/prosilver/theme/common.css
Items in CDB with really long titles (like totally inappropriate titles that aren't really titles but in fact descriptions, but what can you do) break the flow and layout of the CDB.
This PR fixes that by truncating and using an ellipsis on long-winded titles, so they won't break our layout in the way seen below:
> Fix quickview title overflow issues

- contribution/extension/prevalidator.php
- contribution/extension/type.php
Fix an issue in phpBB 3.2 where EPV output, which contains CLI formatting such as `<success>` was now being encoded to HTML entities, and thus rendering `<success>`, e.g.
> Fix output of EPV

- styles/prosilver/template/common/topic_list.html
Topic icons should open 1st unread post, just as happens in pro silver forums.
> Topic icons link to 1st unread post

- ext.php
During enabling the ["autoload"](https://github.com/phpbb/customisation-db/blob/3.2.x/composer.json#L70) is not handled which is why the constants need to be included manually. This should fix the error reported here: https://www.phpbb.com/community/viewtopic.php?p=14613446#p14613446
> Include constants during enabling

- controller/contribution/contribution.php
`$session_id` defaults to `false` which appends the global `$_SID` to download and announcement links. Passing an empty string instead will omit the sid entirely.
> Remove sid from download and announcement links in version_check files

- styles/prosilver/template/common/topic_list.html
Topic status icons still don't link to unread post correctly.
> Fix topic icons linking to new posts (again)

- controller/contribution/contribution.php
Updating so ext manager will be able to show users the correct update for their installed branch of phpbb.
This makes it so the phpBB version(s) the ext is validated for are used as the branch keys, e.g.:
```json
{
"3.1": {
"current": "1.0.5",
"download": "https://www.phpbb.com/customise/db/download/1",
"announcement": "https://www.phpbb.com/customise/db/extension/foo/",
"eol": null,
"security": false
},
"3.2": {
"current": "2.0.1",
"download": "https://www.phpbb.com/customise/db/download/2",
"announcement": "https://www.phpbb.com/customise/db/extension/foo/",
"eol": null,
"security": false
}
}
```
> Use phpbb version branches as the branch keys

- attachment/plupload.php
- attachment/uploader.php
- controller/index.php
- includes/objects/revision.php
https://tracker.phpbb.com/browse/CUSTDB-732
Using `isset` on the `$ext_config` object returns the wrong boolean result in PHP 7. I do not understand why, it may have to do with all the magic used to access the data in $ext_config. Maybe there's a better way, I don't know but in the mean time, replacing asset with a comparison against null also solves the issue in PHP 7.
Specifically these changes fix the problems where uploading a new contribution or revision fails under PHP 7.
> Fix PHP7 issues with isset on $ext_config

- cache/service.php
Namespaced static methods must be fully qualified if passed as string. I've used the `::class` approach as it's shorter.
https://tracker.phpbb.com/browse/CUSTDB-755
> Fix warning when sorting versions

- styles/prosilver/theme/common.css
Turns this malarkey:
Into this:
> Allow download button to grow in height if needed

- includes/overlords/contribs.php
Don't show contribs that have only unvalidated revision(s) for the given branch (this only applies to regular users, titania moderators will still see contribs with unvalidated revisions on the given branch).
https://tracker.phpbb.com/projects/CUSTDB/issues/CUSTDB-741
> Only get validated revisions with branch sorts

- config/routes/contribution.yml
- config/routes/general.yml
- config/routes/manage.yml
Note EPV can not be updated until after this PR is merged. When EPV is updated it will install Symfony 3 components that will break things because of the deprecated YAML code that this PR fixes.
> Fix issues with outdated titania routes

- contribution/extension/type.php
To make composer/installers work, the type has to be `phpbb-extension`.
> Force package type to phpbb-extension

- styles/prosilver/template/plupload.html
When submitting a new revision, S_ATTACH_DATA is not defined, which turns this:
```
data: {S_ATTACH_DATA}
}
```
to this invalid JS Code:
```
data:
}
```
resulting in the entire `phpbb.plupload` object being undefined.
> Set default value if S_ATTACH_DATA is not defined

- event/main_listener.php
- includes/core/phpbb.php
- includes/objects/revision.php
- includes/tools/diff.php
- language/en/manage.php
So Titania comes with a diff class that makes use of phpBB's core files for diffing that was written in 2008 but was never used. I updated it only where necessary and didn't overhaul it completely.
Notes:
* Previously, each entry in a diff result had a header along the lines of:
```
Index: file.php
=====================================
```
I removed this.
* The resulting diff always included unchanged files. I added a switch to the diff class to be able to configure it to skip equal files, making the diff smaller and more readable.
* Including phpBB's core files for diffing threw an error about redeclaring classes when using Titania's `_include()` method, which is why I added a new optional argument to skip auto-including. I'm not sure if there's a better way to solve this.
* The `code` …
> Repack diff

- config/config.php
- includes/objects/revision.php
- includes/tools/diff.php
@vinny reported a problem [in the other PR](https://github.com/phpbb/customisation-db/pull/238#issuecomment-331608863). In his first repack that resulted in an empty diff, a GIF image was deleted from the package. phpBB's differ doesn't skip binary files, and so the diff got corrupted by the null bytes in the GIF header. In the debugger the `$diff` value was truncated, I'm not sure why it ended up being empty in the post.
As a primitive solution for this, I added a fixed set of file extensions that are included in the diff. Files with other extensions are **not** listed in the diff.
> Only diff whitelisted files when repacking

- contribution/extension/type.php
- language/en/types/extension.php
These changes make sure that:
- the version property in composer.json is present
- the version property in composer.json and the revision version entered by the user are the same
- the version is stable
The code of the `is_stable_version()` method was taken from [here](https://github.com/phpbb/mpv/blob/master/includes/tests/tests_modx.php#L181-L227) and was found by @paul999 within 17 nanoseconds.
> Run various checks on extension revision version

- config/console.yml
- console/command/extension/repack.php
- includes/objects/queue.php
- language/en/console.php
There are two issues I haven't been able to figure out so far:
* When passing a message with `-m "Message"` the Extensions Robot creates a post in the validation discussion topic. However, its post count isn't increased.
* I tried to fix generating routes as explained [here](http://symfony.com/doc/current/console/request_context.html) but it doesn't seem to work. Specifically, the `["extra"]["version-check"]` object of the `revision_composer_json` value in the database contains wrong data after running the command:
* `"host"` is `null`
* `"directory"` has the absolute path on the server prepended: `/32/db/extension/post_numbers` becomes `/vagrant/www/32/db/extension/post_numbers`
Any hints on how to get those issues fixed?
> CLI command for repacking extensions

- controller/contribution/revision.php
Look at the most recent revision for a contribution to find the previously selected branches, and then auto-select them for a new revision.
Don't try and auto-select anything if it's the first revision, eg. the condition `if (sizeof($this->contrib->revisions))` must be satisfied.
https://tracker.phpbb.com/projects/CUSTDB/issues/CUSTDB-737
> Auto-select previously selected phpBB branches

- manage/tool/composer/rebuild_repo.php
This would need to be tested on phpBB.com.
Go to `Manage > Administration > Rebuild Composer repository`
Then check the files created in `ext > phpbb > titania > composer_packages > prod > packages-extension-1.json`
Verify that the extensions listed in them have correct contrib and download URLs, e.g:
```
"homepage": "https://www.phpbb.com/customise/db/extension/ads/",
"dist": {
"url": "https://www.phpbb.com/customise/db/download/156996/composer",
"type": "zip"
}
```
Unfortunately, I have no idea why @prototech hard coded this, but it should not be needed.
> Remove hardcoded repository links

- assets/javascript/ajax.js
- styles/prosilver/template/index_body.html
- styles/prosilver/theme/common.css
One hack on .com is the page title "Customisations Database" is removed...probably to save space under the navbar and still have room for links to Support Topics and Queue Stats.
This PR will aim to restore the intended page title and move those ugly links to a more suitable location, in this case, the side bar.
Here is a before image:
And here is what an after image would look like:
> Some navigation adjustments

- config/services.yml
- controller/helper.php
- event/main_listener.php
- includes/objects/topic.php
When a user is removed from a group, do a permissions check to see if they can view any queues still (if so they are a team member, if not they wouldn't be). If they cannot view any queues then remove their queue subscription.
* Fixes "Team-level subscription not removed when user leaves team", https://tracker.phpbb.com/browse/CUSTDB-742
* Fixes "Negative number of replies", https://tracker.phpbb.com/browse/CUSTDB-382
> Remove queue subscription on team removal

- includes/overlords/contribs.php
From https://tracker.phpbb.com/browse/CUSTDB-711
I wasn't able to replicate the first dot point, but I was for the second. Presumably there are reasons why someone might want to make a category invisible without totally cutting off access to contribs inside, so what I've done is made it so that the contribs from the hidden categories won't show on the "all" listing or on the parent category listing either. So the only way you can view it is if you explicitly go into that hidden category (eg. maybe someone wants to keep it private and supplies a direct link to trusted people or something).
How it looks now:
> Fix for contribs in hidden categories still showing everywhere

- styles/prosilver/template/queue_stats_body.html
- styles/prosilver/theme/common.css
- styles/prosilver/theme/responsive.css
https://tracker.phpbb.com/projects/CUSTDB/issues/CUSTDB-780
The queue stats weren't displaying properly for smaller displays. This change makes it look better for four screen sizes:
* Very small (385px width or less)
* Small (385-520)
* Medium (520-890)
* Large (890px and larger)
* This is the default, the other three settings I added media queries for in `responsive.css`.
The stats graph and legend is centre aligned now, and I've split the approval/denial rate graph into its own section, so it should look like this now:
> CUSTDB-780 - Responsive design for queue stats

- attachment/uploader.php
Full discussion at https://tracker.phpbb.com/projects/CUSTDB/issues/CUSTDB-765
I think this might be the reason why the attachment comments become inverted upon saving. The comment_list[] indexes were empty - the template was expecting `ASSOC_INDEX` but that wasn't defined when assigning the template vars.
> CUSTDB-765 - Missing index on attachment comment field

- contribution/translation/prevalidator.php
Before passing the ISO to the translation validator, convert the hyphens to underscores to match the directory names mandated by phpBB language packs.
> Replace hyphens with underscores for languages with a long ISO

- entity/package.php
To have a better idea of what's happening in the `restore_root()` method, some example paths:
```
$directory      = "vendor/ext"
$new_name       = "vendor/ext"
$temp_path      = "./ext/phpbb/titania/files/contrib_temp/abc_123"
$copy_path      = "./ext/phpbb/titania/files/contrib_temp/abc_123_repack/"
$copy_root_path = "./ext/phpbb/titania/files/contrib_temp/abc_123_repack/vendor/ext"
$root_path      = "./ext/phpbb/titania/files/contrib_temp/abc_123/vendor/ext"
$new_root_path  = "./ext/phpbb/titania/files/contrib_temp/abc_123/vendor/ext"
```
> Use rename instead of mirror for package temp folders

- includes/overlords/contribs.php
As of now `3Di` renders as `3di` in the feed.
```
<entry>
<author><name><![CDATA[3di]]></name></author>
```
> Fix ATOM feed author username

- contribution/extension/type.php
- language/en/types/extension.php
This change warns users if the display name inside the composer.json file doesn't match the extension name.
https://tracker.phpbb.com/projects/CUSTDB/issues/CUSTDB-795
> [CUSTDB-795] Check extension name against display name

- config/config.php
- includes/objects/author.php
- migrations/drop_phpbb_user_id.php
- styles/prosilver/template/authors/author_details.html
I found this hardcoded phpbb.com setting in titania itself. It’s 12 year old code and does not even appear to be in use anyway (on phpbb.com).
It also seemed to have a specific `phpbb_user_id` field in addition to the normal `user_id`. I can't see how it's used anywhere except as part of this little hack, which from the template usage, does not even appear to be in use on phpbb.com.
So I'm removing all of it. But am curious to know what was actually being stored in the `phpbb_user_id` field, if anything at all? Is it just `0` or is it the same as the `user_id` or something totally different?
> Remove old unused phpbb.com hack

- contribution/extension/type.php
For example, for an extension display name `A & B`, `$data['extra']['display-name']` is `A & B` (as loaded from `composer.json`) but  `$contrib->contrib_name` is `A &amp; B` so the comparison fails.
I'm using `ENT_COMPAT` because that's what the `$request->variable()` method passes to `htmlspecialchars()` when fetching the value.
> Support characters in extension display name that are HTML-entity-encoded

- sort.php
Where'd the right chevron icon go?
> Fix pagination

- config/services.yml
- event/main_listener.php
- includes/overlords/posts.php
This change means when someone clicks the PM button for a poster in a Titania support topic, it quotes the post like it does in the main forums.
These are the tests I ran, obviously the logic around checking access level is the key part of this because we don't want people to be able to just guess a post id and put it in the URL to see something that's private.
|  | Public | Author | Teams
| ------------- | ------------- | ------------- | ------------- |
| Quoting a public post | CAN SEND | CAN SEND | CAN SEND
| Quoting a authors-only post | CANNOT SEND | CAN SEND | CAN SEND
| Quoting a teams-only post | CANNOT SEND | CANNOT SEND | CAN SEND
Screenshot:
https://tracker.phpbb.com/projects/CUSTDB/issues/CUSTDB-799
> [CUSTDB-799] Quote post text when sending PM from Titania

- includes/overlords/users.php
Fixes a bug whereby hidden online statuses weren't respected (due to a missing array key).
My testing after applying the fix:
|  | Admin | Registered User | Guest
| ------------- | ------------- | ------------- | ------------- |
| Can see the online badge when user sets themselves to hidden (and logs back in) | YES | NO | NO
| Can see the online badge when user sets themselves to visible | YES | YES | YES
https://tracker.phpbb.com/projects/CUSTDB/issues/CUSTDB-803
> [CUSTDB-803] Fix online status bug

- controller/author.php
Fix a permissions bug on the create page. Even if the `u_titania_contrib_submit` permission was set to "no", a faulty `if` statement was letting it through. More information is available on the ticket at https://tracker.phpbb.com/projects/CUSTDB/issues/CUSTDB-800
Now if a user without permission views the page, they will see the standard unauthorised message.
> [CUSTDB-800] Show unauthorised message if user cannot view create page

- message/message.php
On the contribution list, when you hover over a contrib image, and the image disappears to reveal an excerpt of the contrib description, IMG and FLASH BBCodes were not being removed since phpBB 3.2. This fixes that.
> Fix BBCodes in Contrib Excerpts

- styles/prosilver/theme/common.css
- styles/prosilver/theme/responsive.css
The CSS class `.contrib-quickview` has some visual bugs which leaves some empty blocks, which is Fixed.
Best regards 👍
> Fix `.contrib-quickview`

- config/config.php
- config/controllers.yml
- config/services.yml
- controller/manage/config_settings.php
So with this, you would need to go to the Administration->Configuration Settings and just submit the form once. That will restore settings, and move the more complex array based settings from config to config_text.
> Store array based configs in config_text table

- styles/prosilver/template/common/topic_list.html
Noticed by @Crizz0, there was a bug on the Titania topics list whereby the question mark icon to show that there's unapproved posts wasn't appearing. 
Now it works correctly again:
> Bug fix to show unapproved icon on topics list

- styles/prosilver/theme/common.css
Making this PR against 3.2.x as that's still the default — is that what I should be doing?
---
Currently, the UI renders the BBCode and HTML replacement wrapped in a `<code>` element, but no `<pre>` element, so whitespace is collapsed. This makes complex HTML less readable, and can even lead to semantic differences. For example:
```html
<script>
console.log(1)
console.log(2)
</script>
```
With whitespace collapsed, newlines are rendered as spaces when copying and pasting, so the two lines of JS are concatenated into one, causing a syntax error:
```html
<script> console.log(1) console.log(2) </script>
```
Another example that causes discrepancies even without semicolon-less JS:
```html
<pre>
anything
indented
here
</pre>
```
This PR fixes the problem by adding `white-space: pre-wrap` CSS …
> Fix BBCode whitespace display

- styles/prosilver/theme/common.css
Images that are placed inside extension descriptions overflow the description area and hang off the side of the page. This is kind of a rare bug due to the fact not many people put images in the descriptions.
This is what it looks like on mobile (broken):
This is what it looks like on mobile (fixed):
A simple fix to prevent images expanding passed their maximum width for the container.
> Fix issue with images in extension descriptions

- console/command/composer/rebuild_repo.php
- manage/tool/composer/rebuild_repo.php
- manage/tool/contribution/resync_count.php
- manage/tool/contribution/update_release_topics.php
- manage/tool/search/reindex.php
- manage/tool/topic/rebuild_urls.php
- manage/tool/topic/resync_dots.php
- sync.php
Tool commands were using a removed Symfony 2 component, needs to be updated for Symfony 3. Also some mysql/php failures fixed too.
> Fix Titania's failing Tool commands

- language/en/types/extension.php
`By submitting this revision you agree to abide by the Extensions database policies and that your extension conforms to and follows the phpBB 3.2 Coding Guidelines.`
=> 
`By submitting this revision you agree to abide by the Extensions database policies and that your extension conforms to and follows the phpBB 3.3 Coding Guidelines.`
> Use wording and link to coding guidelines 3.3 instead of 3.2
